# Shared jobs that are generally applicable to everyone
# Assumes a 'base' job defined elsewhere
- job:
    name: verify-test-success
    description: |
      Run simple commands as test.

      To use this, set the ``test_command`` variable.
    run: playbooks/verify-test-success/run.yaml
    vars:
      test_command: "touch sriov_file"

- job:
    name: goodbyejob
    run: playbooks/goodbyejob.yaml

- project:
    check:
      jobs:
        - verify-test-success
        - goodbyejob

#- job:
#    name: tap-as-a-service-dsvm-intel-sriov
#    description: |
#      setup devstack and test port mirroring
#      on intel nic using tempest.
#    pre-run: playbooks/inteltaptest/pre.yaml
#    run: playbooks/inteltaptest/run.yaml
#
#- job:
#    name: run-test-command
#    description: |
#      Run simple command as test.
#
#      To use this, set the ``test_command`` variable.
#    run: playbooks/run-test-command/run.yaml
#    vars:
#      test_command: "touch sriov_file"

